# Generated by Django 4.2.1 on 2023-06-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_price_product_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_desc', models.CharField(max_length=500)),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
