# Generated by Django 4.2.1 on 2023-06-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('category_desc', models.CharField(max_length=500)),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
