# Generated by Django 4.2.1 on 2023-06-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_display_product_delete_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
