# Generated by Django 4.2.1 on 2023-07-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_address_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AddField(
            model_name='address',
            name='add_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
