# Generated by Django 4.2.1 on 2023-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_display_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_product',
            name='sub_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
