# Generated by Django 4.2.1 on 2023-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_item',
            field=models.CharField(default='', max_length=100),
        ),
    ]
