# Generated by Django 4.2.1 on 2023-06-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_item_product_sub_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='discount_percent',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='og_price',
            field=models.IntegerField(default=0),
        ),
    ]
