# Generated by Django 4.2.1 on 2023-06-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_discount_percent_alter_product_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Seller',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_expiry',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_manufactured',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
