# Generated by Django 4.2.1 on 2023-06-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_product_seller_product_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
