# Generated by Django 4.2.1 on 2023-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_product_id', models.IntegerField(blank=True, default=0, max_length=100, null=True)),
            ],
        ),
    ]
