# Generated by Django 4.2.1 on 2023-06-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='added_product_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
