# Generated by Django 4.2.1 on 2023-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_cartitem_added_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_product_id',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
        ),
    ]
