# Generated by Django 4.2.1 on 2023-07-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_email_address_username_alter_address_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='add_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
