# Generated by Django 4.2.1 on 2023-07-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_address_add_id_alter_address_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='add_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
